version: '3.8'

services:
  postgres:
    image: postgis/postgis:15-3.3
    container_name: mbv-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: mbv_user
      POSTGRES_PASSWORD: mbv_pass
      POSTGRES_DB: mbv_db
    ports:
      - '5432:5432'
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: mbv-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data

volumes:
  redis_data:
